name: Set Main Page

on:
  push:
    branches:
      - main  # Adjust this to match your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set Main Page
        run: echo "index.html" > .nojekyll
